name: deploy-aws-lambda-test

on:
  push:
    branches:
      - deploy-test

jobs:
  call-test-workflow:
   # https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
   uses: ./.github/workflows/run-tests.yml

  deploy:
    needs: call-test-workflow
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@master

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.0b3
          virtualenvs-create: true
          virtualenvs-in-project: true # could this be bloating the ZIP file?
          installer-parallel: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: upgrade NPM
        run: npm install -g npm@latest

      - name: Verify NPM
        run: npm doctor

      - name: Install Dependencies
        run: npm install

      - name: List packages
        run: npm ls	

      - name: Serverless Doctor
        run: npm run-script sls_doctor

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Serverless Deploy ....
        run: npm run-script deploy
        env:
          STAGE: "test"
